dataset:
  name: CICIDS
  dataset_dir: data/CSV/CICIDS/
  processed_dir: data/Graph/CICIDS/
  label_level: Application
  per_class: 1000
  pkt_num: 3
  window_t: 10

model:
  name: FIR-GNN
  hidden: 32
  heads: 2

train:
  exp: AC
  lr: 0.01
  epochs: 300
  label_ratio: 0.8
  device: cuda
